name: Node.js CI

on:
 [push]
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          # Remove cache here, it causes error without package-lock.json in root

      - name: Set up Node.js cache in /src
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: src/package-lock.json  # Make sure this file exists!

      - name: Install dependencies
        working-directory: ./src
        run: |
          npm ci
          npm install bgutils-js jsonfile

      - name: Build the project
        working-directory: ./src
        run: npm run build

      - name: Run tests
        working-directory: ./src
        run: npm test
