name: Test Discord Bot and Dashboard

on:
 {push}
permissions:
  contents: read
jobs:
  test:
    runs-on: Linux

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '20.x' # Use Node.js 16.x which supports the ??= operator
    - name: Installing...
      run: |
        cd ./src
        npm install bgutils-js jsonfile express
    - name: starting
      run: |
        cd ./src
        node index.js &
        sleep 10
        IP_ADDRESS=$(hostname -I)
        curl http://$IP_ADDRESS:3000 || echo "Started"
      env:
        TOKEN: ${{ secrets.TOKEN }}
        CLIENTID: ${{  secrets.CLIENTID}}
