name: Test Discord Bot and Dashboard

on:
  {push}

jobs:
  test:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Installing...
      run: |
        cd /home/vasilew/actions-runner/_work/DBD2/src
        npm install bgutils-js jsonfile express
    - name: starting
      run: |
        cd /home/vasilew/actions-runner/_work/DBD2/src
        node index.js &
        sleep 10
        IP_ADDRESS=$(echo %HOSTNAME% | get-ipv4)
        curl http://$IP_ADDRESS:3000 || echo "Started"
      env:
        TOKEN: ${{ secrets.TOKEN }}
