name: Test Discord Bot and Dashboard

on:
  { push}

jobs:
  test:
    runs-on: Linux

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Installing...
      run: |
        cd ./src
        npm install --ignore-scripts
        npm install bgutils-js jsonfile express --ignore-scripts
    - name: starting
      run: |
       cd src
        node index.js
        sleep 10
        IP_ADDRESS=$(get-ipv4)
        curl http://$IP_ADDRESS:3000
      env:
        TOKEN: ${{ secrets.TOKEN }}
