name: Test Discord Bot and Dashboard

on:
 push:
  branches: [ "main","dev" ]
permissions:
  contents: read
jobs:
  Dashboard-Setup:
    runs-on: Linux

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '20.x' # Use Node.js 16.x which supports the ??= operator
    - name: Installing...
      run: |
        cd ./src
        npm install bgutils-js jsonfile express
    - name: starting
      run: |
        node index.js
        sleep 10
        IP_ADDRESS=$(hostname -I)
        curl --resolve http://$IP_ADDRESS:3000 || echo "Started"
      env:
        token: ${{ secrets.TOKEN }}
        clientId: ${{  secrets.CLIENTID}}
        clientSecret: ${{ secrets.CLIENTSECRET}}
        database: ${{secrets.DATABASE}}
        host: ${{secrets.HOST}}
        user: ${{secrets.USER}}
        password: ${{secrets.PASSWORD}}
        secret: ${{secrets.SECRET}}
